import { Component } from '@angular/core';
import { UserCardComponent } from '../user-card/user-card.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [UserCardComponent, UserCardComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  users: any[] = [
    {
      id: 1,
      firstName: 'Emily',
      lastName: 'Johnson',
      maidenName: 'Smith',
      age: 28,
      gender: 'female',
      email: 'emily.johnson@x.dummyjson.com',
      phone: '+81 965-431-3024',
      username: 'emilys',
      password: 'emilyspass',
      birthDate: '1996-5-30',
      image: 'https://i.pravatar.cc/150?img=1',
    },
    {
      id: 2,
      firstName: 'Michael',
      lastName: 'Williams',
      maidenName: '',
      age: 35,
      gender: 'male',
      email: 'michael.williams@x.dummyjson.com',
      phone: '+49 258-627-6644',
      username: 'michaelw',
      password: 'michaelwpass',
      birthDate: '1989-8-10',
      image: 'https://i.pravatar.cc/150?img=2',
    },
    {
      id: 3,
      firstName: 'Sophia',
      lastName: 'Brown',
      maidenName: '',
      age: 42,
      gender: 'female',
      email: 'sophia.brown@x.dummyjson.com',
      phone: '+81 210-652-2785',
      username: 'sophiab',
      password: 'sophiabpass',
      birthDate: '1982-11-6',
      image: 'https://i.pravatar.cc/150?img=3',
    },
    {
      id: 4,
      firstName: 'James',
      lastName: 'Davis',
      maidenName: '',
      age: 45,
      gender: 'male',
      email: 'james.davis@x.dummyjson.com',
      phone: '+49 614-958-9364',
      username: 'jamesd',
      password: 'jamesdpass',
      birthDate: '1979-5-4',
      image: 'https://i.pravatar.cc/150?img=4',
    },
    {
      id: 5,
      firstName: 'Emma',
      lastName: 'Miller',
      maidenName: 'Johnson',
      age: 30,
      gender: 'female',
      email: 'emma.miller@x.dummyjson.com',
      phone: '+91 759-776-1614',
      username: 'emmaj',
      password: 'emmajpass',
      birthDate: '1994-6-13',
      image: 'https://i.pravatar.cc/150?img=5',
    },
    {
      id: 6,
      firstName: 'Olivia',
      lastName: 'Wilson',
      maidenName: '',
      age: 22,
      gender: 'female',
      email: 'olivia.wilson@x.dummyjson.com',
      phone: '+91 607-295-6448',
      username: 'oliviaw',
      password: 'oliviawpass',
      birthDate: '2002-4-20',
      image: 'https://i.pravatar.cc/150?img=6',
    },
    {
      id: 7,
      firstName: 'Alexander',
      lastName: 'Jones',
      maidenName: '',
      age: 38,
      gender: 'male',
      email: 'alexander.jones@x.dummyjson.com',
      phone: '+61 260-824-4986',
      username: 'alexanderj',
      password: 'alexanderjpass',
      birthDate: '1986-10-20',
      image: 'https://i.pravatar.cc/150?img=7',
    },
    {
      id: 8,
      firstName: 'Ava',
      lastName: 'Taylor',
      maidenName: '',
      age: 27,
      gender: 'female',
      email: 'ava.taylor@x.dummyjson.com',
      phone: '+1 458-853-7877',
      username: 'avat',
      password: 'avatpass',
      birthDate: '1997-8-25',
      image: 'https://i.pravatar.cc/150?img=8',
    },
    {
      id: 9,
      firstName: 'Ethan',
      lastName: 'Martinez',
      maidenName: '',
      age: 33,
      gender: 'male',
      email: 'ethan.martinez@x.dummyjson.com',
      phone: '+92 933-608-5081',
      username: 'ethanm',
      password: 'ethanmpass',
      birthDate: '1991-2-12',
      image: 'https://i.pravatar.cc/150?img=9',
    },
    {
      id: 10,
      firstName: 'Isabella',
      lastName: 'Anderson',
      maidenName: 'Davis',
      age: 31,
      gender: 'female',
      email: 'isabella.anderson@x.dummyjson.com',
      phone: '+49 770-658-4885',
      username: 'isabellad',
      password: 'isabelladpass',
      birthDate: '1993-6-10',
      image: 'https://i.pravatar.cc/150?img=10',
    },
    {
      id: 11,
      firstName: 'Liam',
      lastName: 'Garcia',
      maidenName: '',
      age: 29,
      gender: 'male',
      email: 'liam.garcia@x.dummyjson.com',
      phone: '+92 870-217-6201',
      username: 'liamg',
      password: 'liamgpass',
      birthDate: '1995-6-6',
      image: 'https://i.pravatar.cc/150?img=11',
    },
    {
      id: 12,
      firstName: 'Mia',
      lastName: 'Rodriguez',
      maidenName: '',
      age: 24,
      gender: 'female',
      email: 'mia.rodriguez@x.dummyjson.com',
      phone: '+49 989-461-8403',
      username: 'miar',
      password: 'miarpass',
      birthDate: '2000-8-4',
      image: 'https://i.pravatar.cc/150?img=12',
    },
    {
      id: 13,
      firstName: 'Noah',
      lastName: 'Hernandez',
      maidenName: '',
      age: 40,
      gender: 'male',
      email: 'noah.hernandez@x.dummyjson.com',
      phone: '+49 393-605-6968',
      username: 'noahh',
      password: 'noahhpass',
      birthDate: '1984-6-5',
      image: 'https://i.pravatar.cc/150?img=13',
    },
    {
      id: 14,
      firstName: 'Charlotte',
      lastName: 'Lopez',
      maidenName: 'Martinez',
      age: 36,
      gender: 'female',
      email: 'charlotte.lopez@x.dummyjson.com',
      phone: '+44 373-953-5028',
      username: 'charlottem',
      password: 'charlottempass',
      birthDate: '1988-6-8',
      image: 'https://i.pravatar.cc/150?img=14',
    },
    {
      id: 15,
      firstName: 'William',
      lastName: 'Gonzalez',
      maidenName: '',
      age: 32,
      gender: 'male',
      email: 'william.gonzalez@x.dummyjson.com',
      phone: '+81 905-252-7319',
      username: 'williamg',
      password: 'williamgpass',
      birthDate: '1992-3-27',
      image: 'https://i.pravatar.cc/150?img=15',
    },
    {
      id: 16,
      firstName: 'Avery',
      lastName: 'Perez',
      maidenName: '',
      age: 25,
      gender: 'female',
      email: 'avery.perez@x.dummyjson.com',
      phone: '+61 731-431-3457',
      username: 'averyp',
      password: 'averyppass',
      birthDate: '1999-3-10',
      image: 'https://i.pravatar.cc/150?img=16',
    },
  ];
  temp = [...this.users];

  filterUsersByUsername(event: any): void {
    event.preventDefault();
    this.users = this.temp.filter((user) =>
      user.username.toLowerCase().includes(event.target?.value.toLowerCase())
    );
  }

  title = 'Lab-2';
}
